# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= ENV['WAF_DATABASE_PASSWORD'] %>

development:
  <<: *default
  reconnect: false
  database: <%= ENV['TARGET_DB'] == 'localhost' ? 'waf_admin_rails_development' : (ENV['TARGET_DB'] == 'staging' ? ENV['STAGING_DB'] : ENV['PROD_DB']) %>
  pool: 5
  username: <%= ENV['TARGET_DB'] == 'localhost' ? nil : (ENV['TARGET_DB'] == 'staging' ? ENV['STAGING_DB_USER'] : ENV['PROD_DB_USER']) %>
  password: <%= ENV['TARGET_DB'] == 'localhost' ? nil : (ENV['TARGET_DB'] == 'staging' ? ENV['STAGING_DB_PASSWORD'] : ENV['PROD_DB_PASSWORD']) %>
  host: <%= ENV['TARGET_DB'] == 'localhost' ? nil : (ENV['TARGET_DB'] == 'staging' ? ENV['STAGING_DB_HOST'] : ENV['PROD_DB_HOST']) %>

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: waf_admin_test

production:
  <<: *default
  database: waf_rails_production
  username: waf_rails
  password: <%= ENV['WAF_RAILS_DATABASE_PASSWORD'] %>
